FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /source

# TODO: Copy source code to workdir 
COPY

# TODO: Restore Dot Net Layers and publish
RUN 

WORKDIR /app

# Launch .NET app by providing the command
CMD
